@startuml

title __SRC's Class Diagram__\n

  namespace  {
    class MainStage {
        {static} + main()
        + start()
    }
  }
  

  namespace  {
    class Scene1Controller {
        - BFP : double
        - BFPResult : TextField
        - BMI : double
        - BMIResult : TextField
        - BMR : double
        - BMRResult : TextField
        - LBM : double
        - LBMResult : TextField
        - RWL : double
        - RWLResult : TextField
        - age : int
        - constant1 : double
        - gender : String
        - height : double
        - inputAge : TextField
        - inputGender : ChoiceBox<String>
        - inputHeight : TextField
        - inputInsertArea : VBox
        - inputLabel : VBox
        - inputName : TextField
        - inputWeight : TextField
        - name : String
        - nextButton : Button
        - result : Button
        - root : Parent
        - scene : Scene
        - stage : Stage
        - weight : double
        + calculate()
        + getGender()
        + initialize()
        + switchtoScene2()
    }
  }
  

  namespace  {
    class Scene2Controller {
        ~ calAmount : double
        ~ calBurn : double
        ~ quantityOfBread : double
        ~ quantityOfBurger : double
        ~ quantityOfChicken : double
        ~ quantityOfCoffee : double
        ~ quantityOfFish : double
        ~ quantityOfNoodle : double
        ~ quantityOfRice : double
        ~ quantityOfTea : double
        - averageBMR : TextField
        - bodybuild : CheckBox
        - bread : CheckBox
        - breadQuantity : TextField
        - burger : CheckBox
        - burgerQuantity : TextField
        - calculateButton : Button
        - calorieBurn : TextField
        - calorieDeficit : TextField
        - calorieIntake : TextField
        - chicken : CheckBox
        - chickenQuantity : TextField
        - coffee : CheckBox
        - coffeeQuantity : TextField
        - comment : Label
        - fish : CheckBox
        - fishQuantity : TextField
        - jog : CheckBox
        - noodle : CheckBox
        - noodleQuantity : TextField
        - plainWater : CheckBox
        - rice : CheckBox
        - riceQuantity : TextField
        - rope : CheckBox
        - swim : CheckBox
        - tea : CheckBox
        - teaQuantity : TextField
        - walk : CheckBox
        + avgBMR()
        + calculateDeficit()
        + tocalCalorieBurn()
        + totalCaloriIntake()
    }
  }
  

  MainStage -up-|> javafx.application.Application
  Scene1Controller .up.|> javafx.fxml.Initializable


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
